DevTalles/Models/Categoria.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace DevTalles.Models
{
    public class Categoria
    {
        public int CategoriaId { get; set; }
        
        [Required(ErrorMessage ="El campo Categoria es obligatorio")]
        [Remote(action: "ValidarNombre", controller: "Categoria")]
        public string NombreCategoria { get; set; }

        [Required(ErrorMessage = "El campo Orden es obligatorio")]
        [Range(1, int.MaxValue,ErrorMessage ="El valor debe de ser entre {1} y {2}")]
        public int MostrarOrden { get; set; }


        public IEnumerable<SubCategoria> SubCategoria { get; set; }

    }
}

DevTalles/Controllers/CategoriaController.cs
using DevTalles.Data;
using DevTalles.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace DevTalles.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class CategoriaController : Controller
    {
        private readonly ApplicationDbContext _db;


        //por medio de inyeccion de dependencia accedemos al DbContext para manipular los datos
        public CategoriaController(ApplicationDbContext db)
        {
            _db = db;
        }

        //Get Mostramos la lista de Categorias en la vista index
        public async Task<IActionResult> Index()
        {
            var ListaCategoria =await _db.Categorias.ToListAsync();

            return View(ListaCategoria);
        }


        //Get Mostramos el formulario para crear categoria
        public  IActionResult Crear()
        {
            

            return View();
        }

        //Esta Accion Agrega el Registro en la base de datos


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult>Crear(Categoria model)
        {
            if (!ModelState.IsValid) { return NotFound(); }

           await _db.Categorias.AddAsync(model);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");



        }
        //Esta Accion muestra el Registro en la vista
        public IActionResult Editar(int? id)
        {
            if (id is null || id == 0 )
            {
                return NotFound();
            }

            var categoriadb =_db.Categorias.Find(id);
            if (categoriadb is null)
            {
                return NotFound();
            }

            return View(categoriadb);
        }


        //Esta Accion Actualiza el Registro en la base de datos
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult>Editar(Categoria categoria)
        {
            if (!ModelState.IsValid)
            {
                return NotFound();
            }
            _db.Categorias.Update(categoria);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }



       

        

        //Esta Accion Elimina el Registro en la base de datos

        [HttpDelete]
        
        public async Task<ActionResult> Eliminar(int id)
        {
            var categoria = _db.Categorias.Find(id);

            var subcategoria = new List<SubCategoria>();

            subcategoria = _db.SubCategorias.Where(s => s.CategoriaId == id).ToList();

            foreach (var item in subcategoria)
            {
                _db.SubCategorias.Remove(item);
            }


             _db.Categorias.Remove(categoria);
            
            await _db.SaveChangesAsync();

            return Json(new { success = true , message ="Categoria borrada con exito" });



        }



        // Esta es una validacion a nivel del controlador valida que no se inserte el mismo nombre dos veses

        [HttpGet]
        public async Task<IActionResult> ValidarNombre(string NombreCategoria)
        {

            var existe = await _db.Categorias.AnyAsync(name => name.NombreCategoria == NombreCategoria);

            if (existe)
            {
                return Json($"El nombre {NombreCategoria} Ya Existe");
            }
            return Json(true);
        }



    }
}

DevTalles/Controllers/SubCategoriaController.cs
using DevTalles.Data;
using DevTalles.Models;
using DevTalles.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace DevTalles.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class SubCategoriaController : Controller
    {
        private readonly ApplicationDbContext _db;

        public SubCategoriaController(ApplicationDbContext db)
        {
            _db = db;
        }


        //Mostramos y agrupamos las distintas categorias con las subcategorias correspondientes
        public async Task<IActionResult> Index()
        {

            var categoriasRelacionadas = await _db.SubCategorias.Include(tc => tc.Categoria).ToListAsync();

            var model = categoriasRelacionadas.GroupBy(c => c.Categoria).Select(grupo => new CategoriasSubCategoriaViewModel { Categoria = grupo.Key.NombreCategoria, SubCategorias = grupo.AsEnumerable() }).ToList();

            return View(model);
        }


        //Get Mostramos el formulario para crear subCategoria
        public IActionResult Crear()
        {
            SubCategoriaCreacionViewModel model = new SubCategoriaCreacionViewModel();

            model.DropdownCategoria = DropdownCategoria();
            return View(model);
        }

        //Esta Accion Agrega el Registro en la base de datos


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Crear(SubCategoriaCreacionViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.DropdownCategoria = DropdownCategoria();
                return View(model);

            }






            _db.SubCategorias.Add(model.subCategoria);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");



        }
        //Esta Accion muestra el Registro en la vista
        public IActionResult Editar(int? id)
        {
            var model = new SubCategoriaCreacionViewModel()
            {
                subCategoria = new SubCategoria(),
                DropdownCategoria = DropdownCategoria()
            };



            if (id is null || id == 0)
            {
                return NotFound();
            }


            model.subCategoria = _db.SubCategorias.Find(id);





            if (model.subCategoria is null)
            {
                return NotFound();
            }

            return View(model);
        }


        //Esta Accion Actualiza el Registro en la base de datos
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Editar(SubCategoria subCategoria)
        {
            if (!ModelState.IsValid)
            {
                return NotFound();
            }
            _db.SubCategorias.Update(subCategoria);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }




        [HttpDelete]
        //Esta Accion Elimina el Registro en la base de datos


        public async Task<ActionResult> Eliminar(int id)
        {

            var model = _db.SubCategorias.Find(id);
            if (model is null) { return NotFound(); }

            _db.SubCategorias.Remove(model);
            await _db.SaveChangesAsync();

            return Json(new { success = true });




        }








        //Validamos que no se repita el nombre

        [HttpGet]
        public async Task<IActionResult> ValidarNombre(string nombre)
        {

            var existe = await _db.SubCategorias.AnyAsync(name => name.Nombre == nombre);
            if (existe)
            {
                return Json($"El nombre {nombre} Ya Existe");
            }
            return Json(true);
        }

        public IEnumerable<SelectListItem> DropdownCategoria()
        {
            return _db.Categorias.Select(c => new SelectListItem(c.NombreCategoria, c.CategoriaId.ToString()));
        }
    }
}

DevTalles/Views/Categoria/Crear.cshtml
    @model Categoria

@{
    ViewData["Title"] = "Crear";
    
}

<form method="post" asp-action="Crear">
    <div class="border p-3 ">

        <div asp-validation-summary="ModelOnly" class="text-danger">
        </div>

        <div class="form-group row">
            <h2 class="text-info pl-3">Nueva Categoria</h2>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="NombreCategoria" class="form-label">Nombre Categoria</label>
                    <input asp-for="NombreCategoria" class="form-control" />
                    <span asp-validation-for="NombreCategoria" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="MostrarOrden" class="form-label">Orden</label>
                    <input asp-for="MostrarOrden" class="form-control" />
                    <span asp-validation-for="MostrarOrden" class="text-danger"></span>
                </div>
            </div>
            <br />
            <div class="d-grid gap-2 d-md-block">
                <button type="submit" class="btn btn-primary">Crear Nueva</button>
                <a asp-controller="Categoria" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>

        </div>


    </div>

</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

DevTalles/Views/Categoria/Editar.cshtml
@model Categoria

@{
    ViewData["Title"] = "Editar";
    
}

<form method="post" asp-action="Editar">
    <input asp-for="CategoriaId" hidden />
    <div class="border p-3 ">

        <div asp-validation-summary="ModelOnly" class="text-danger">
        </div>

        <div class="form-group row">
            <h2 class="text-info pl-3">Editar Categoria</h2>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="NombreCategoria" class="form-label">Nombre Categoria</label>
                    <input asp-for="NombreCategoria" class="form-control" />
                    <span asp-validation-for="NombreCategoria" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="MostrarOrden" class="form-label">Orden</label>
                    <input asp-for="MostrarOrden" class="form-control" />
                    <span asp-validation-for="MostrarOrden" class="text-danger"></span>
                </div>
            </div>
            <br />
            <div class="d-grid gap-2 d-md-block">
                <button type="submit" class="btn btn-primary">Actualizar</button>
                <a asp-controller="Categoria" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>

        </div>


    </div>

</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

DevTalles/Views/Categoria/Index.cshtml
@using DevTalles.Models.ViewModels;
@model IEnumerable<Categoria>
@{
    ViewData["Title"] = "Lista de Categorias";
}



<div class="container p-3">

    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Lista de Categorias</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Categoria" asp-action="Crear" class="btn btn-primary">
                <i class="fas fa-plus"></i>  Nueva Categoria
            </a>

            <a asp-controller="SubCategoria" asp-action="Index" class="btn btn-success">
                <i class="fas fa-plus"></i>  Agrega  SubCategorias
            </a>
        </div>
    </div>
    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Nombre Categoria
                    </th>
                    <th>
                        orden
                    </th>
                    <th>

                    </th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    var id = item.CategoriaId;
                    var ruta = $"/Categoria/Eliminar/{id}";

                    <tr>
                        <th width="50%">@item.NombreCategoria</th>
                        <th width="30%">@item.MostrarOrden</th>
                        <th class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Categoria" asp-action="Editar" asp-route-Id="@item.CategoriaId" class="btn btn-primary mx-2">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a class="btn btn-danger mx-2" onclick=confirmDelete("@ruta")>
                                    <i class="fas fa-trash-alt"></i>
                                </a>

                            </div>

                        </th>
                    </tr>
                }
            </tbody>

        </table>
    }
    else
    {
        <p>No hay registros de Categoria</p>
    }

</div>




@section Scripts{

    <script>
        function confirmDelete(url) {
            Swal.fire({
                title: '¿Estás seguro?',
                text: 'Esto Eliminara la Categoria',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Sí, Eliminar',
                cancelButtonText: 'Cancelar'
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({

                        type: 'DELETE',
                        url: url,
                        success: function (data) {

                            if(data.success){
                                Swal.fire(
                                    'Exitoso!',
                                    'La categoria se eliminó correctamente.',
                                    'success'
                                );
                               
                            }
                          
                            
                        }
                    });

                    setTimeout(function () {
                        window.location.reload();
                    }, 1000)
                   
                }
            });
        }
    </script>




}