DevTalles/Models/SubCategoria.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DevTalles.Models
{
    public class SubCategoria
    {
        [Key]
        public int SubCategoriaId { get; set; }

        [Required(ErrorMessage = "El Nombre de la Sub Categoria es obligatorio.")]
        [Display(Name ="SubCategoria")]
        [Remote(action:"ValidarNombre",controller:"SubCategoria")]
        public string Nombre { get; set; }


        public int CategoriaId { get; set; }

        [ForeignKey("CategoriaId")]
        public Categoria? Categoria { get; set; }
    }
}

DevTalles/Controllers/CategoriaController.cs
using DevTalles.Data;
using DevTalles.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace DevTalles.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class CategoriaController : Controller
    {
        private readonly ApplicationDbContext _db;


        //por medio de inyeccion de dependencia accedemos al DbContext para manipular los datos
        public CategoriaController(ApplicationDbContext db)
        {
            _db = db;
        }

        //Get Mostramos la lista de Categorias en la vista index
        public async Task<IActionResult> Index()
        {
            var ListaCategoria =await _db.Categorias.ToListAsync();

            return View(ListaCategoria);
        }


        //Get Mostramos el formulario para crear categoria
        public  IActionResult Crear()
        {
            

            return View();
        }

        //Esta Accion Agrega el Registro en la base de datos


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult>Crear(Categoria model)
        {
            if (!ModelState.IsValid) { return NotFound(); }

           await _db.Categorias.AddAsync(model);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");



        }
        //Esta Accion muestra el Registro en la vista
        public IActionResult Editar(int? id)
        {
            if (id is null || id == 0 )
            {
                return NotFound();
            }

            var categoriadb =_db.Categorias.Find(id);
            if (categoriadb is null)
            {
                return NotFound();
            }

            return View(categoriadb);
        }


        //Esta Accion Actualiza el Registro en la base de datos
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult>Editar(Categoria categoria)
        {
            if (!ModelState.IsValid)
            {
                return NotFound();
            }
            _db.Categorias.Update(categoria);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }



       

        

        //Esta Accion Elimina el Registro en la base de datos

        [HttpDelete]
        
        public async Task<ActionResult> Eliminar(int id)
        {
            var categoria = _db.Categorias.Find(id);

            var subcategoria = new List<SubCategoria>();

            subcategoria = _db.SubCategorias.Where(s => s.CategoriaId == id).ToList();

            foreach (var item in subcategoria)
            {
                _db.SubCategorias.Remove(item);
            }


             _db.Categorias.Remove(categoria);
            
            await _db.SaveChangesAsync();

            return Json(new { success = true , message ="Categoria borrada con exito" });



        }



        // Esta es una validacion a nivel del controlador valida que no se inserte el mismo nombre dos veses

        [HttpGet]
        public async Task<IActionResult> ValidarNombre(string NombreCategoria)
        {

            var existe = await _db.Categorias.AnyAsync(name => name.NombreCategoria == NombreCategoria);

            if (existe)
            {
                return Json($"El nombre {NombreCategoria} Ya Existe");
            }
            return Json(true);
        }



    }
}

DevTalles/Controllers/SubCategoriaController.cs
using DevTalles.Data;
using DevTalles.Models;
using DevTalles.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace DevTalles.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class SubCategoriaController : Controller
    {
        private readonly ApplicationDbContext _db;

        public SubCategoriaController(ApplicationDbContext db)
        {
            _db = db;
        }


        //Mostramos y agrupamos las distintas categorias con las subcategorias correspondientes
        public async Task<IActionResult> Index()
        {

            var categoriasRelacionadas = await _db.SubCategorias.Include(tc => tc.Categoria).ToListAsync();

            var model = categoriasRelacionadas.GroupBy(c => c.Categoria).Select(grupo => new CategoriasSubCategoriaViewModel { Categoria = grupo.Key.NombreCategoria, SubCategorias = grupo.AsEnumerable() }).ToList();

            return View(model);
        }


        //Get Mostramos el formulario para crear subCategoria
        public IActionResult Crear()
        {
            SubCategoriaCreacionViewModel model = new SubCategoriaCreacionViewModel();

            model.DropdownCategoria = DropdownCategoria();
            return View(model);
        }

        //Esta Accion Agrega el Registro en la base de datos


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Crear(SubCategoriaCreacionViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.DropdownCategoria = DropdownCategoria();
                return View(model);

            }






            _db.SubCategorias.Add(model.subCategoria);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");



        }
        //Esta Accion muestra el Registro en la vista
        public IActionResult Editar(int? id)
        {
            var model = new SubCategoriaCreacionViewModel()
            {
                subCategoria = new SubCategoria(),
                DropdownCategoria = DropdownCategoria()
            };



            if (id is null || id == 0)
            {
                return NotFound();
            }


            model.subCategoria = _db.SubCategorias.Find(id);





            if (model.subCategoria is null)
            {
                return NotFound();
            }

            return View(model);
        }


        //Esta Accion Actualiza el Registro en la base de datos
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Editar(SubCategoria subCategoria)
        {
            if (!ModelState.IsValid)
            {
                return NotFound();
            }
            _db.SubCategorias.Update(subCategoria);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }




        [HttpDelete]
        //Esta Accion Elimina el Registro en la base de datos


        public async Task<ActionResult> Eliminar(int id)
        {

            var model = _db.SubCategorias.Find(id);
            if (model is null) { return NotFound(); }

            _db.SubCategorias.Remove(model);
            await _db.SaveChangesAsync();

            return Json(new { success = true });




        }








        //Validamos que no se repita el nombre

        [HttpGet]
        public async Task<IActionResult> ValidarNombre(string nombre)
        {

            var existe = await _db.SubCategorias.AnyAsync(name => name.Nombre == nombre);
            if (existe)
            {
                return Json($"El nombre {nombre} Ya Existe");
            }
            return Json(true);
        }

        public IEnumerable<SelectListItem> DropdownCategoria()
        {
            return _db.Categorias.Select(c => new SelectListItem(c.NombreCategoria, c.CategoriaId.ToString()));
        }
    }
}

DevTalles/Views/SubCategoria/Crear.cshtml
@using DevTalles.Models.ViewModels;
@model SubCategoriaCreacionViewModel

@{
    ViewData["Title"] = "Crear";

}

<form method="post" asp-action="Crear" id="formulario">
    <div class="border p-3 ">

        <div asp-validation-summary="ModelOnly" class="text-danger">
        </div>

        <div class="form-group row">
            <h2 class="text-info pl-3">Nueva subCategoria</h2>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="subCategoria.Nombre" class="form-label">Nombre</label>
                    <input asp-for="subCategoria.Nombre" class="form-control" />
                    <span asp-validation-for="subCategoria.Nombre" class="text-danger"></span>
                </div>
                <div class="col-md-6">
                    <label asp-for="subCategoria.CategoriaId" class="form-label">Nombre</label>
                    <select asp-for="subCategoria.CategoriaId" class="form-select" asp-items="Model.DropdownCategoria">
                        <option disabled selected>--Seleccione una categoria</option>
                    </select>
                    <span asp-validation-for="subCategoria.CategoriaId" class="text-danger"></span>
                </div>
            </div>

            <br />
            <div class="d-grid gap-2 d-md-block">
                <button type="submit" class="btn btn-primary">Crear Nuevo</button>
                <a asp-controller="SubCategoria" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>

        </div>


    </div>

</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }


    <script>


        document.addEventListener('DOMContentLoaded',function(){

            const forms = document.getElementById('formulario');

            forms.addEventListener('submit', function(e){
                e.preventDefault();
                Swal.fire({
                    title: '¿Estás seguro?',
                    text: 'Esto enviará la orden',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Sí, enviar',
                    cancelButtonText: 'Cancelar'
                }).then(result) => {


                    if(result.isConfirmed){
                        Swal.fire(
                            'Exitoso!',
                            'Se ha agregado un nuevo Registro!.',
                            'success'
                        )

                        setTimeout(function () {
                            form.submit();
                        }, 1000)


                    }

                }


            });





        });


    </script>
}

DevTalles/Views/SubCategoria/Editar.cshtml
@using DevTalles.Models.ViewModels;
@model SubCategoriaCreacionViewModel
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" asp-action="Editar">
    <input asp-for="subCategoria.SubCategoriaId" hidden />
    <div class="border p-3 ">

        <div asp-validation-summary="ModelOnly" class="text-danger">

        </div>

        <div class="form-group row">
            <h2 class="text-info pl-3">Editar SubCategoria</h2>
        </div> 
                 
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="subCategoria.Nombre" class="form-label">Nombre</label>
                    <input asp-for="subCategoria.Nombre" class="form-control" />
                    <span asp-validation-for="subCategoria.Nombre" class="text-danger"></span>
                </div>
                <div class="col-md-6">
                    <label asp-for="subCategoria.CategoriaId" class="form-label">Nombre</label>
                    <select asp-for="subCategoria.CategoriaId" class="form-select" asp-items="Model.DropdownCategoria">
                        <option disabled selected>--Seleccione una categoria</option>
                    </select>
                    <span asp-validation-for="subCategoria.CategoriaId" class="text-danger"></span>
                </div>
            </div>
           
            <br />
            <div class="d-grid gap-2 d-md-block">
                <button type="submit" class="btn btn-primary">Actualizar</button>
                <a  asp-action="Index" class="btn btn-success">Regresar</a>
            </div>

        </div>


    </div>   

</form>

@section Scripts {
    @{ <partial name="_ValidationScriptsPartial" /> }
}

DevTalles/Views/SubCategoria/Eliminar.cshtml
@model SubCategoria

@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" asp-action="Eliminar">
    <input asp-for="SubCategoriaId" hidden />
    <div class="border p-3 ">

        <div asp-validation-summary="ModelOnly" class="text-danger">

        </div>

        <div class="form-group row">
            <h2 class="text-danger pl-3">Esta Seguro de Eliminar esta SubCategoria?</h2>
        </div> 
                 
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Nombre" class="form-label">Nombre</label>
                    <input asp-for="Nombre" disabled class="form-control"/>

                </div>
            </div>
            
            <br />
            <div class="d-grid gap-2 d-md-block">
                <button type="submit" class="btn btn-danger">Eliminar</button>
                <a  asp-action="Index" class="btn btn-success">Regresar</a>
            </div>

        </div>


    </div>   

</form>

@section Scripts {
    @{ <partial name="_ValidationScriptsPartial" /> }
}

DevTalles/Views/SubCategoria/Index.cshtml
@using DevTalles.Models.ViewModels;
@model IEnumerable<CategoriasSubCategoriaViewModel>

@{
    ViewData["Title"] = "Index";

}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h1 class="text-primary">Lista de SubCategorias</h1>
            <h3>
                Esta es una lista donde agrupamos las SubCategorias
                dentro de las distintas Categorias
            </h3>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="SubCategoria" asp-action="Crear" class="btn btn-primary">
                <i class="fas fa-plus"></i>  Nueva SubCategorias
            </a>  <a asp-controller="Categoria" asp-action="Index" class="btn btn-outline-warning text-dark">
                <i class="fa-sharp fa-solid fa-arrow-left"></i> Regresar a Categoria
            </a>
        </div>
    </div>
    <br />

    @if (Model.Count() > 0)
    {
        <div class="accordion acordeon-Categorias">

            @foreach (var categoria in Model)
            {
                <div class="accordion-item">
                    <h2 class="accordion-header" id="CabeceraUno">
                        @{
                            //creamos el identificador del boton para el acordion
                            var id = categoria.Categoria.Replace(" ", "");
                            var target = "#" + id;
                        }



                        <button class="accordion-button bg-dark text-white " data-bs-toggle="collapse" data-bs-target="@target">
                            @categoria.Categoria

                        </button>
                    </h2>

                    <div id="@id" class="accordion-collapse collapse show">
                        <div>
                            <ul class="list-group">
                                @foreach (var subcategoria in categoria.SubCategorias)
                                {
                                    var idSubcategoria = subcategoria.SubCategoriaId;
                                    var ruta = $"/SubCategoria/Eliminar/{idSubcategoria}";


                                    <li class="list-group-item">
                                        <div class="d-flex justify-content-between">
                                            <p>@subcategoria.Nombre</p>
                                            <div>
                                                <a asp-action="Editar" asp-route-id="@subcategoria.SubCategoriaId" class="btn btn-outline-warning me-3">Editar</a>
                                                <a class="btn btn-danger me-3" onclick=eliminar("@ruta")>Eliminar</a>
                                            </div>

                                        </div>



                                    </li>
                                }
                            </ul>
                        </div>

                    </div>
                </div>

            }
        </div>


    }
    else
    {
        <p>No hay registros de SubCategoria</p>
    }

</div>

@section Scripts{
    <script>
        function eliminar(url) {

            Swal.fire({
                title: 'Borrar SubCategoria',
                text: 'Esta seguro de borrar esta SubCategoria??',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Eliminar!'
            }).then((result) => {
                if (result.isConfirmed) {

                    $.ajax({
                        type:'DELETE',
                        url:url,
                        success:function(data){
                            if(data.success){
                                Swal.fire(
                                    'Borrada!',
                                    'Se ha eliminado correctamente.',
                                    'success'
                                )
                            }
                        }
                    });

                     setTimeout(function(){
                            window.location.reload();
                        },1000)


                   
                }
            })


        }
    </script>
}