DevTalles/Controllers/CarroController.cs
using DevTalles.Data;
using DevTalles.Models;
using DevTalles.Models.ViewModels;
using DevTalles.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace DevTalles.Controllers
{
    [Authorize]
    public class CarroController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        [BindProperty]//Para utilizar esta variable en todo el controller y no perder sus datos
        public UsuarioProductoVM usuarioProductoVM { get; set; }

        public CarroController(ApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }


        //Este controller se encarga de obtener los cursos que se encuentran en el carrito de compras almacenado en la sesión del usuario, para devolverlos a la vista Index.

        public IActionResult Index()
        {

            List<CarroCompra> listaCompras = new();

            if (HttpContext.Session.Get<IEnumerable<CarroCompra>>(WC.VariableSession) != null &&
                HttpContext.Session.Get<IEnumerable<CarroCompra>>(WC.VariableSession).Count() > 0)
            {
                listaCompras = HttpContext.Session.Get<List<CarroCompra>>(WC.VariableSession);
            }

            List<int> idsCarroCompra = listaCompras.Select(c => c.CursoId).ToList();

            List<Curso> curso = dbContext.Cursos.Where(c => idsCarroCompra.Contains(c.Id)).ToList();


            return View(curso);
        }


        //Este codigo busca el usuario conectado a la aplicacion y los productos seleccionados
        //en la sesion para luego llenar el viewModel UsuarioProductoVM con los datos del usuario
        //y los cursos seleccionados para mostrarlos en la vista.
        public IActionResult Resumen()
        {

            UsuarioAplicacion usuario;
            if (User.IsInRole(WC.AdminRole))
            {

                //si el usuario es admin y desea actualizar una orden existente
                if (HttpContext.Session.Get<int>(WC.SessionOrdenId) != 0)
                {
                    //obtenemos la orden a actualizar
                    Orden orden = dbContext.Ordenes.Find(HttpContext.Session.Get<int>(WC.SessionOrdenId));


                    //obtenemos el usuario que pertenece ala orden
                    usuario = new UsuarioAplicacion()
                    {
                        Email = orden.Email,
                        NombreCompleto = orden.NombreCompleto,
                        PhoneNumber = orden.Telefono
                    };
                }
                else
                { //si no le damos la opcion al admin que ingrese al usuario
                    usuario = new UsuarioAplicacion();
                }
            }
            else
            {
                //traer usuario conectado ala aplicacion

                var clainUsers = (ClaimsIdentity)User.Identity;
                var clain = clainUsers.FindFirst(ClaimTypes.NameIdentifier);

                usuario = dbContext.UsuariosAplicacion.FirstOrDefault(us => us.Id == clain.Value);
            }


           



            List<CarroCompra> listaCompras = new();

            if (HttpContext.Session.Get<IEnumerable<CarroCompra>>(WC.VariableSession) != null &&
                HttpContext.Session.Get<IEnumerable<CarroCompra>>(WC.VariableSession).Count() > 0)
            {
                listaCompras = HttpContext.Session.Get<List<CarroCompra>>(WC.VariableSession);
            }

            List<int> idsCarroCompra = listaCompras.Select(c => c.CursoId).ToList();



            usuarioProductoVM = new UsuarioProductoVM()
            {
                UsuarioAplicacion = usuario,
                CursosLista = dbContext.Cursos.Where(c => idsCarroCompra.Contains(c.Id)).ToList()

            };

            return View(usuarioProductoVM);
        }


       //Una vez confirmada la orden se guarda la orden y el detalle de la orden en
       //la base de datos 



        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [ActionName("Resumen")]
        public IActionResult ResumenPost(UsuarioProductoVM usuarioProductoVM)
        {
          //Obtenemos el usuario autenticado
            var ClaimUser = (ClaimsIdentity)User.Identity;
            var Claim = ClaimUser.FindFirst(ClaimTypes.NameIdentifier);

            

            



            //Gurdamos la Orden Con la informacion del usuario
            Orden ordenCurso = new Orden()

            {
                UsuarioAplicacionId = Claim.Value,
                NombreCompleto = usuarioProductoVM.UsuarioAplicacion.NombreCompleto,
                Email = usuarioProductoVM.UsuarioAplicacion.Email,
                FechaOrden = DateTime.Now,
                Telefono = usuarioProductoVM.UsuarioAplicacion.PhoneNumber
            };

            dbContext.Ordenes.Add(ordenCurso);
            dbContext.SaveChanges();

            //Grabamos la orden con la data relacionada entre orden y producto

            foreach (var curso in usuarioProductoVM.CursosLista)
            {
                OrdenDetalle ordenDetalle = new OrdenDetalle()
                {
                    OrdenId = ordenCurso.Id,
                    CursoID = curso.Id,
                    UsuarioId = Claim.Value
                    
                    
                };
                dbContext.OrdenDetalles.Add(ordenDetalle);
            }

            dbContext.SaveChanges();

            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");


        }




        //Esta se encarga de eliminar los productos que estan en la vista carro de compras

        public IActionResult Eliminar(int id)
        {
            List<CarroCompra> listCarro = new();
            if (HttpContext.Session.Get<IEnumerable<CarroCompra>>(WC.VariableSession) != null && HttpContext.Session.Get<IEnumerable<CarroCompra>>(WC.VariableSession).Count() > 0)
            {
                listCarro = HttpContext.Session.Get<List<CarroCompra>>(WC.VariableSession);
            }

            listCarro.Remove(listCarro.FirstOrDefault(c => c.CursoId == id));
            HttpContext.Session.Set(WC.VariableSession, listCarro);

            return RedirectToAction("Index");
        }
    }
}

DevTalles/Views/Carro/Confirmacion.cshtml
<div class="text-center">

  
        
        
    
  
   
        <h1 class="text-info">Confirmacion</h1>
        <p>Hemos recibido tu Consulta. Un miembro de nuestro equipo se contactara pronto contigo</p>
    


    <img src="/imagenes/patio.jpg" width="80%" />
</div>

DevTalles/Views/Carro/Index.cshtml
@using DevTalles.Data;


@model IEnumerable<Curso>

@if (Model.Count() > 0)
{
    <form method="post">
        <br />
        <div class="backgroundWhiteBorder">
            <div class="container row">
                <div class="col -8">
                    <div class="card mt-4">
                        <div class="card-header bg-dark text-light ml-0 row container">
                            <div class="col-6">
                                <i class="fa fa-shopping-cart"></i> &nbsp;
                                Carro de Compras
                            </div>
                            <div class="col-6 text-end">

                                <a asp-action="Index" asp-controller="Home" class="btn btn-outline-info btn-sm">Continuar Comprando</a>
                            </div>

                        </div>
                        <div class="card-body">
                            <div class=" d-none d-lg-block">
                                <div class="row " style="color:#821f3d">
                                    <div class="col-lg-2">
                                    </div>


                                    <div class="col-12 col-lg-6">
                                        Detalle de producto
                                    </div>


                                    <div class="col-12 col-lg-2">
                                        Precio de producto
                                    </div>
                                



                                    <div class="col-6 col-sm-4 col-lg-1">
                                    </div>
                                </div>
                            </div>
                   
                            @{
                                var total = 0.0;
                            }
                        <hr />
                        @foreach (var item in Model)
                        {

                                

                                

                            <div class="row my-2 h-100">
                                <div class="col-4 col-md-2 text-center py-2">
                                    <img src="@WC.RutaImagen@item.ImagenUrl" class="rounded" width="90%" />
                                </div>
                                <div class="col-8 col-lg-6">
                                    <h5>@item.NombreProducto</h5>
                                    <div style="font-size:17px;">@item.DescripcionCorta</div>
                                </div>




                                <div class="col-3 col-lg-2 pt-lg-4 m-0" style="font-size:11px;">
                                    <span style="font-size:27px;"> $@item.Precio</span>

                                </div>
                                
                        


                                <div class="col-2 col-lg-1 p-0 pt-lg-4 text-center my-2">
                                    <a asp-action="Eliminar" asp-route-Id="@item.Id" class="btn btn-outline-danger">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </div>
                                
                                
                            </div>
                                total = total + item.Precio;
                            }

                            <div class="col-12 text-end pr-4" style="color:#821f3d">
                                Total Orden: @string.Format("{0:c}", total)
                            </div>
                            
                            
                            <hr />
                            <div/>
                                

                     
                        <div class="card-footer">
                            <div class="row">

                                <div class="col-6 col-md-3 offset-md-9">
                                    <a asp-action="Resumen" class="btn btn-success form-control ">
                                        <span>Continuar</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </form>
}
else
{
    <p>Por favor agregar Productos al Carro</p>
}

DevTalles/Views/Carro/Resumen.cshtml
@using DevTalles.Models.ViewModels;
@model UsuarioProductoVM




<form method="post" asp-controller="Carro" id="payment-form">
    <br />
    <div class="backgroundWhiteBorder">
        <div class="container">
            <div class="card">
                <div class="card-header bg-dark text-light ml-0 row container">
                    <div class="col-6">
                        <i class="fa fa-shopping-cart"></i> &nbsp;
                        Resumen de la Orden
                    </div>
                    <div class="col-6 text-end">
                        <a asp-action="Index" class="btn btn-outline-info btn-sm">Regresar al Carro</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="container rounded p-2">
                        <div class="row">
                            <div class="col-12 col-lg-7 pb-4">
                                <div class="row">
                                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                                        <span class="text-info">Detalle del Usuario:</span>
                                    </h4>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Nombres</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="UsuarioAplicacion.NombreCompleto" type="text" class="form-control" id="nombre" />
                                        <span asp-validation-for="UsuarioAplicacion.NombreCompleto" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Telefono</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="UsuarioAplicacion.PhoneNumber" type="text" class="form-control" id="telefono" />
                                        <span asp-validation-for="UsuarioAplicacion.PhoneNumber" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Email</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="UsuarioAplicacion.Email" type="text" class="form-control" id="email" />
                                        <span asp-validation-for="UsuarioAplicacion.Email" class="text-danger"></span>
                                    </div>
                                </div>


                            </div>
                            <div class="col-12 col-lg-5 row">
                                <div class="col-12">
                                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                                        <span class="text-info">Resumen:</span>
                                    </h4>
                                    <ul class="list-group mb-3">

                                        @for (int i = 0; i < Model.CursosLista.Count(); i++)
                                        {




                                            <li class="list-group-item d-flex justify-content-between">
                                                <input type="hidden" asp-for="@Model.CursosLista[i].Id" />
                                                <input type="hidden" asp-for="@Model.CursosLista[i].NombreProducto" />
                                                <input type="hidden" asp-for="@Model.CursosLista[i].Precio" />



                                                <div>
                                                    <h6 class="my-0">@Model.CursosLista[i].NombreProducto</h6>
                                                    <small class="text-muted">Precio: $@Model.CursosLista[i].Precio</small>
                                                </div>

                                            </li>
                                        }


                                    </ul>
                                </div>



                            </div>
                        </div>
                    </div>
                </div>



                <div class="card-footer">
                    <div class="row">
                        <div class="col-12 col-md-5 offset-md-7">

                            <button type="submit" class="btn btn-primary form-control ">Enviar Orden</button>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>


@section Scripts{
    <script>

        // Espera a que se cargue la página antes de ejecutar cualquier código
        document.addEventListener('DOMContentLoaded', function () {
            // Obtiene el formulario por su ID
            const form = document.querySelector('#payment-form');
            // Agrega un evento al formulario para cuando se envíe
            form.addEventListener('submit', function (event) {
                // Detiene el envío del formulario para poder mostrar la alerta
                event.preventDefault();
                // Muestra la alerta
                Swal.fire({
                    title: '¿Estás seguro?',
                    text: 'Esto enviará la orden',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Sí, enviar',
                    cancelButtonText: 'Cancelar'
                }).then((result) => {
                    // Si el usuario hace clic en el botón "Sí, enviar", envía el formulario
                    if (result.isConfirmed) {

                        Swal.fire(
                            'Exitoso!',
                            'Su Orden se enviado!!.',
                            'success'
                        )

                        setTimeout(function(){
                            form.submit();
                        },1000)
                        
                    }
                });
            });
        });
    </script>

   }