DevTalles/Controllers/CarroController.cs
using DevTalles.Data;
using DevTalles.Models;
using DevTalles.Models.ViewModels;
using DevTalles.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace DevTalles.Controllers
{
    [Authorize]
    public class CarroController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        [BindProperty]//Para utilizar esta variable en todo el controller y no perder sus datos
        public UsuarioProductoVM usuarioProductoVM { get; set; }

        public CarroController(ApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }


        //Este controller se encarga de obtener los cursos que se encuentran en el carrito de compras almacenado en la sesión del usuario, para devolverlos a la vista Index.

        public IActionResult Index()
        {

            List<CarroCompra> listaCompras = new();

            if (HttpContext.Session.Get<IEnumerable<CarroCompra>>(WC.VariableSession) != null &&
                HttpContext.Session.Get<IEnumerable<CarroCompra>>(WC.VariableSession).Count() > 0)
            {
                listaCompras = HttpContext.Session.Get<List<CarroCompra>>(WC.VariableSession);
            }

            List<int> idsCarroCompra = listaCompras.Select(c => c.CursoId).ToList();

            List<Curso> curso = dbContext.Cursos.Where(c => idsCarroCompra.Contains(c.Id)).ToList();


            return View(curso);
        }


        //Este codigo busca el usuario conectado a la aplicacion y los productos seleccionados
        //en la sesion para luego llenar el viewModel UsuarioProductoVM con los datos del usuario
        //y los cursos seleccionados para mostrarlos en la vista.
        public IActionResult Resumen()
        {

            UsuarioAplicacion usuario;
            if (User.IsInRole(WC.AdminRole))
            {

                //si el usuario es admin y desea actualizar una orden existente
                if (HttpContext.Session.Get<int>(WC.SessionOrdenId) != 0)
                {
                    //obtenemos la orden a actualizar
                    Orden orden = dbContext.Ordenes.Find(HttpContext.Session.Get<int>(WC.SessionOrdenId));


                    //obtenemos el usuario que pertenece ala orden
                    usuario = new UsuarioAplicacion()
                    {
                        Email = orden.Email,
                        NombreCompleto = orden.NombreCompleto,
                        PhoneNumber = orden.Telefono
                    };
                }
                else
                { //si no le damos la opcion al admin que ingrese al usuario
                    usuario = new UsuarioAplicacion();
                }
            }
            else
            {
                //traer usuario conectado ala aplicacion

                var clainUsers = (ClaimsIdentity)User.Identity;
                var clain = clainUsers.FindFirst(ClaimTypes.NameIdentifier);

                usuario = dbContext.UsuariosAplicacion.FirstOrDefault(us => us.Id == clain.Value);
            }


           



            List<CarroCompra> listaCompras = new();

            if (HttpContext.Session.Get<IEnumerable<CarroCompra>>(WC.VariableSession) != null &&
                HttpContext.Session.Get<IEnumerable<CarroCompra>>(WC.VariableSession).Count() > 0)
            {
                listaCompras = HttpContext.Session.Get<List<CarroCompra>>(WC.VariableSession);
            }

            List<int> idsCarroCompra = listaCompras.Select(c => c.CursoId).ToList();



            usuarioProductoVM = new UsuarioProductoVM()
            {
                UsuarioAplicacion = usuario,
                CursosLista = dbContext.Cursos.Where(c => idsCarroCompra.Contains(c.Id)).ToList()

            };

            return View(usuarioProductoVM);
        }


       //Una vez confirmada la orden se guarda la orden y el detalle de la orden en
       //la base de datos 



        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [ActionName("Resumen")]
        public IActionResult ResumenPost(UsuarioProductoVM usuarioProductoVM)
        {
          //Obtenemos el usuario autenticado
            var ClaimUser = (ClaimsIdentity)User.Identity;
            var Claim = ClaimUser.FindFirst(ClaimTypes.NameIdentifier);

            

            



            //Gurdamos la Orden Con la informacion del usuario
            Orden ordenCurso = new Orden()

            {
                UsuarioAplicacionId = Claim.Value,
                NombreCompleto = usuarioProductoVM.UsuarioAplicacion.NombreCompleto,
                Email = usuarioProductoVM.UsuarioAplicacion.Email,
                FechaOrden = DateTime.Now,
                Telefono = usuarioProductoVM.UsuarioAplicacion.PhoneNumber
            };

            dbContext.Ordenes.Add(ordenCurso);
            dbContext.SaveChanges();

            //Grabamos la orden con la data relacionada entre orden y producto

            foreach (var curso in usuarioProductoVM.CursosLista)
            {
                OrdenDetalle ordenDetalle = new OrdenDetalle()
                {
                    OrdenId = ordenCurso.Id,
                    CursoID = curso.Id,
                    UsuarioId = Claim.Value
                    
                    
                };
                dbContext.OrdenDetalles.Add(ordenDetalle);
            }

            dbContext.SaveChanges();

            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");


        }




        //Esta se encarga de eliminar los productos que estan en la vista carro de compras

        public IActionResult Eliminar(int id)
        {
            List<CarroCompra> listCarro = new();
            if (HttpContext.Session.Get<IEnumerable<CarroCompra>>(WC.VariableSession) != null && HttpContext.Session.Get<IEnumerable<CarroCompra>>(WC.VariableSession).Count() > 0)
            {
                listCarro = HttpContext.Session.Get<List<CarroCompra>>(WC.VariableSession);
            }

            listCarro.Remove(listCarro.FirstOrDefault(c => c.CursoId == id));
            HttpContext.Session.Set(WC.VariableSession, listCarro);

            return RedirectToAction("Index");
        }
    }
}

DevTalles/Controllers/CursosController.cs
using DevTalles.Data;
using DevTalles.Models;
using DevTalles.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace DevTalles.Controllers
{
    [Authorize(Roles=WC.AdminRole)]
    public class CursosController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly IWebHostEnvironment hostEnvironment;

        public CursosController(ApplicationDbContext db, IWebHostEnvironment hostEnvironment)
        {
            this.db = db;
            this.hostEnvironment = hostEnvironment;
        }

        //Esta Accion muestra la vista index con una tabla donde se muestran todos los CursosLista
        public IActionResult Index()
        {

            IEnumerable<Curso> Cursos = db.Cursos.Include(c => c.Categoria).Include(cs => cs.SubCategoria);
            return View(Cursos);
        }





        //UPSERT Es una Accion que sirve para actualizar campos o agregar campos validando si se pasa el ID
        
        public async Task<IActionResult> Upsert(int? id)
        {
            var model = new CursoViewModel()
            {
                Curso = new Curso(),
                DropDowmCategoria = DropdownCategoria(),
                DropDowmSubCategoria = DropdownSubCategoria()
            };



            if (id == null)
            {
                return View(model);

            }
            else
            {
                model.Curso = await db.Cursos.FindAsync(id);



                if (model.Curso is null)
                {
                    return NotFound();
                }
                return View(model);
            }

        }


        //Esta accion de tipo Post Realiza la correspondiente Actualizacion o Agregacion de datos en la base de datos


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(CursoViewModel model)
        {


            //Validamos que el model sea valido
            if (!ModelState.IsValid)
            {


                model.DropDowmCategoria = DropdownCategoria();
                model.DropDowmSubCategoria = DropdownSubCategoria();

                return View(model);

            }
            else
            {//Comenzamos a ver si se ha cargado algun archivo en la vista

                var file = HttpContext.Request.Form.Files;

                //obtenemos la ruto principal donde se guardara la imagen en este caso la wwwRoot
                var RootPath = hostEnvironment.WebRootPath;

                //si el id de curso es igual a cero significa que crearemos un nuevo curso 
                if (model.Curso.Id == 0)
                {



                    //validamos que se guarde una imagen identificando que el usuario desea agregar una imagen

                    if (file.Count > 0)
                    {
                        string Upload = RootPath + WC.RutaImagen;
                        string filename = Guid.NewGuid().ToString();
                        var extencion = Path.GetExtension(file[0].FileName);


                        using (FileStream fileStream = new FileStream(Path.Combine(Upload, filename + extencion), FileMode.Create))
                        {
                            file[0].CopyTo(fileStream);
                        }

                        model.Curso.ImagenUrl = filename + extencion;
                        db.Cursos.Add(model.Curso);

                        await db.SaveChangesAsync();
                        return RedirectToAction("Index");

                    }
                    else
                    {
                        //en nuestro sistema requerimos que se seleccione una imagen por lo cual si no se hace regresamos ala misma vista pasandole el model

                        model.DropDowmCategoria = DropdownCategoria();
                        model.DropDowmSubCategoria = DropdownSubCategoria();
                        return View(model);

                    }






                }
                else
                {
                    //actualizamo un curso ya existente


                    var cursoDb = await db.Cursos.AsNoTracking().FirstOrDefaultAsync(c => c.Id == model.Curso.Id);


                    //Actualizamos el curso si agrega una nueva imagen se borra la anterior y se guarda la nueva
                    if (file.Count > 0)
                    {
                        string Upload = RootPath + WC.RutaImagen;
                        string filename = Guid.NewGuid().ToString();
                        string extencion = Path.GetExtension(file[0].FileName);

                        var urlimagenAnterior = Path.Combine(Upload, cursoDb.ImagenUrl);



                        if (System.IO.File.Exists(urlimagenAnterior))
                        {
                            System.IO.File.Delete(urlimagenAnterior);
                        }


                        using (FileStream fileStream = new FileStream(Path.Combine(Upload, filename + extencion), FileMode.Create))
                        {
                            file[0].CopyTo(fileStream);
                        }

                        model.Curso.ImagenUrl = filename + extencion;
                        db.Cursos.Update(model.Curso);
                        await db.SaveChangesAsync();

                    }
                    else
                    {
                        //en nuestro sistema requerimos que se seleccione una imagen por lo cual si no se hace regresamos ala misma vista pasandole el model




                        model.Curso.ImagenUrl = cursoDb.ImagenUrl;
                        db.Cursos.Update(model.Curso);
                        await db.SaveChangesAsync();
                        return RedirectToAction("Index");
                    }

                }
                return View(model);



            }




        }



        //Esta accion es para Eliminar los datos de la base de datos

        [HttpDelete]


        public async Task<IActionResult> Delete(int id)
        {
            var CursoDB = await db.Cursos.FindAsync(id);

            if (CursoDB == null)
            {
                return Json(new { success = false, message = "Error al borrar tu Curso" });
            }
            else
            {
                var wwwroot = hostEnvironment.WebRootPath;
                var upload = wwwroot + CursoDB.ImagenUrl;


                if (System.IO.File.Exists(upload))
                {
                    System.IO.File.Delete(upload);
                }
                db.Cursos.Remove(CursoDB);
                await db.SaveChangesAsync();

                return Json(new { success = true, message = "Curso eliminado Correctamente" });
            }
        }


        [HttpGet]
        public async Task<JsonResult> ObtenerSubCategoria(int id)
        {
            var subcategorias = db.SubCategorias.Where(sc => sc.CategoriaId == id);

            IEnumerable<SelectListItem> categorias = subcategorias.Select(sb => new SelectListItem(sb.Nombre, sb.SubCategoriaId.ToString()));
            return Json(categorias);
        }




        //metodos para llenar el SelectList

        public IEnumerable<SelectListItem> DropdownCategoria()
        {
            return db.Categorias.Select(c => new SelectListItem(c.NombreCategoria, c.CategoriaId.ToString()));
        }
        public IEnumerable<SelectListItem> DropdownSubCategoria()
        {
            return db.SubCategorias.Select(c => new SelectListItem(c.Nombre, c.SubCategoriaId.ToString()));
        }


    }
}

DevTalles/Controllers/OrdenesController.cs
using DevTalles.Data;
using DevTalles.Models;
using DevTalles.Models.ViewModels;
using DevTalles.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data.Common;
using System.Threading.Tasks.Dataflow;

namespace DevTalles.Controllers
{
    [Authorize(Roles =WC.AdminRole)]
    public class OrdenesController : Controller
    {
        private readonly ApplicationDbContext db;

        [BindProperty]
        public OrdenVM OrdenViewModel { get; set; }

        public OrdenesController(ApplicationDbContext _db)
        {
            db = _db;
        }


        public IActionResult Index()
        {
            return View();
        }  
        
        public IActionResult Detalle(int id)
        {

            OrdenViewModel = new OrdenVM()
            {
                Orden = db.Ordenes.Find(id),
                OrdenDetalle = db.OrdenDetalles.Include(o => o.Curso).Where(o => o.OrdenId == id).ToList()
            };



            return View(OrdenViewModel);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [ActionName("Detalle")]
        public IActionResult DetalleOrden()
        {

            


            List<CarroCompra> carroCompras = new();
            OrdenViewModel.OrdenDetalle = db.OrdenDetalles.Where(c => c.OrdenId ==OrdenViewModel.Orden.Id).ToList();

            foreach (var detalle in OrdenViewModel.OrdenDetalle)
            {
                CarroCompra compra = new()
                {
                    CursoId = detalle.CursoID
                };

                carroCompras.Add(compra);
            }
            HttpContext.Session.Clear();
            HttpContext.Session.Set(WC.VariableSession, carroCompras);
            HttpContext.Session.Set(WC.SessionOrdenId, OrdenViewModel.Orden.Id);
            return RedirectToAction("Index", "Carro");

        }


        [HttpPost]
        public IActionResult Eliminar()
        {
            Orden orden = db.Ordenes.FirstOrDefault(o => o.Id == OrdenViewModel.Orden.Id);
            List<OrdenDetalle> ordenDetalle = db.OrdenDetalles.Where(od => od.OrdenId == orden.Id).ToList();


            db.OrdenDetalles.RemoveRange(ordenDetalle);
            db.Ordenes.Remove(orden);
            db.SaveChanges();

            return View("Index");
        }





        #region
        [HttpGet]

        public IActionResult GetAll()
        {
            return Json(new {data = db.Ordenes.ToList()});
        }
        #endregion





    }
}

DevTalles/Views/Shared/_CardProductos.cshtml
@using DevTalles.Data;
@model Curso


<!-- Card-->


<li class="curso  m-2 filter @Model.Categoria.NombreCategoria.Replace(' ','_')" style="position:relative" >
 
        <img class="card-img-top w-100"
             src="@WC.RutaImagen@Model.ImagenUrl"
             alt="imagen curso" style="max-height:140px; overflow:hidden" 
             />



        <div class="card-body d-flex flex-column  " style="max-height:230px">
            <label class="titulo fw-bold" style="max-height:80px; overflow:hidden">@Model.NombreProducto</label>

            <div class="flex-grow-1 mb-3">
                <p class=" m-0 fw-bold">@Model.Categoria.NombreCategoria</p>
                <p class="instructor">@Model.SubCategoria.Nombre</p>

                


                
            </div>


          
        </div>


    <a asp-action="Detalle" asp-route-Id="@Model.Id" class="btn btn-outline-dark " style="position:absolute; bottom:0">@Model.Precio USD$ <span style="text-decoration:line-through">200 USD$</span></a>
       
            
   
</li>

DevTalles/Views/Shared/_CardProductosUser.cshtml
@using DevTalles.Data;
@model OrdenDetalle

<div class="col-lg-4 col-md-6 pb-4 filter @Model.Curso.Categoria.NombreCategoria.Replace(' ','_')">
    <!-- Card-->
    <div style="max-height:500px; min-height:500px"  class="card bg-white rounded shadow-sm" style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-10">
                <label class="float-left">@Model.Curso.NombreProducto</label></div>
            <div class="col-2">
                <label class="float-right">
                    <span class="text-info h5">@Model.Curso.Precio</span>
                </label>

            </div>
        </div>
        <img class="card-img-top img-fluid d-block mx-auto mb-3 w-100 overflow-hidden" style="max-height:300px; " src="@WC.RutaImagen@Model.Curso.ImagenUrl" alt="Imagen Card">
        <div class="card-body p-1 px-3 row" >
            <div class="col-6">
                <span class="badge p-2 border w-100 text-white" style="background-color:rgb(24, 20, 36)">@Model.Curso.Categoria.NombreCategoria</span>
            </div>
         
            <div class="col-12 pt-2" style="font-size:13px; text-align:justify">
                <p> @Model.Curso.DescripcionCorta</p>
            </div>
            <div class="col-12 p-1">
                <a asp-action="DetalleCursoUsuario" asp-route-Id="@Model.Curso.Id" class="btn btn-dark form-control btn-sm p-2" style="height:40px">Iniciar Curso</a>
            </div>
        </div>
    </div>
</div>

DevTalles/Views/Shared/_Layout.cshtml
@using DevTalles.Data;
@using DevTalles.Utilities;
@inject IHttpContextAccessor httpAccesor


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DevTalles</title>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/sweetalert2/sweetalert2.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DevTalles.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css" />
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+HarunoUmi:wght@400;700&amp;family=Open+Sans&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/app.css" asp-append-version="true" />

</head>
<body>



    <header class="header container-fluid ">
        <div class="d-flex justify-content-between align-items-center p-3 shadow-sm">

            <a asp-action="Index" asp-controller="Home" class="fs-3 fw-bold m-0 me-4 nav-link"> <span class="text-success">D</span>evtalles</a>

            <ul class="navbar-nav ">
                @if (User.IsInRole(WC.AdminRole))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Administrar Contenido
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-area="" asp-controller="Categoria" asp-action="index">Categoria</a></li>
                            <li><a class="dropdown-item" asp-area="" asp-controller="SubCategoria" asp-action="index">SubCategorias</a></li>
                            <li><a class="dropdown-item" asp-area="" asp-controller="Cursos" asp-action="index">Cursos</a></li>
                            <li><a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Crear Nuevo Usuario</a></li>
                            <li><a class="dropdown-item" asp-area="" asp-controller="Ordenes" asp-action="Index">Orden</a></li>
                            <li><a class="dropdown-item" asp-area="" asp-controller="venta" asp-action="Index">Venta</a></li>

                        </ul>
                    </li>
                   
                }
            </ul>

            <form class="flex-grow-1 mx-3">
                <input type="search"
                       class="form-control bg-light"
                       placeholder="Busca cualquier cosa" />
            </form>


            @if (User.IsInRole(WC.ClienteRole))
            {

                <nav class="d-flex">
                    @*comprueba si hay una sesión de CarroCompras en la solicitud. Si hay una sesión, se muestra
                el número de artículos en el carrito de la compra. Si no hay una sesión, se muestra un enlace de carrito de compras con 0 artículos.*@

                    @if (httpAccesor.HttpContext.Session.Get<List<CarroCompra>>(@WC.VariableSession) != null)
                    {

                        <a asp-action="Index" asp-controller="Carro" class="text-dark nav-link">
                            @{
                                var count = httpAccesor.HttpContext.Session.Get<List<CarroCompra>>(@WC.VariableSession).Count();
                            }
                            <i class="fas fa-shopping-cart "></i>  (@count)
                        </a>
                    }
                    else
                    {
                        <a class="text-dark nav-link" href="#">

                            <i class="fas fa-shopping-cart"></i> &nbsp; (0)
                        </a>
                    }

                    <a class="text-dark nav-link" asp-action="UsuarioCurso" asp-controller="Home">

                        Mis Cursos
                    </a>

                </nav>
            }


            <nav class="mx-3">
                <partial name="_LoginPartial" />
            </nav>
        </div>
    </header>



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>




    <footer class="bg-dark py-5">
        <div class="container-xl">
            <div class="row align-items-start">
                <nav class="col-md-4 d-flex">
                    
                    <a  href="https://www.udemy.com/teaching/?ref=teach_footer" class="text-light text-decoration-none nav-link">Enseña en U</a>
                    <a href="https://www.udemy.com/mobile/" class="text-light text-decoration-none nav-link">Consigue la App</a>
                    <a asp-action="Index" asp-controller="Home" class="btn btn-outline-light">Inicio</a>
             
                </nav>

         

            
            </div>
        </div>

        <div class="container-xl mt-5 d-flex justify-content-between align-items-center">
            <p class="text-light fs-3 fw-bold"> <span class="text-success">D</span>evtalles</p>

            <p class="text-light">&copy; Devtalles 2023.</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/sweetalert2/sweetalert2.min.js"></script>

    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    
    

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DevTalles/Views/Shared/_SeccionCurso.cshtml
@using DevTalles.Data;
@{
    var img = "persona3.png";
}
<section class="descuentos container-xl mb-4">
    <div class="row justify-content-around align-items-lg-end bg-light">
        <div class="col-lg-4 shadow bg-white texto-descuentos">
            <div class="p-3">
                <h2>Disfruta de los mejores Cursos de Programación</h2>
                <p class="descripcion">Cursos desde 10 USD$. Selecciona el que mas te Guste en cualquier curso.</p>

                <input placeholder="¿Qué quieres aprender?"
                       type="search"
                       class="form-control bg-light buscar" />
            </div>
        </div>

        <div class="col-lg-5">
            <img class="img-fluid" src="@WC.RutaImagen@img" alt="imagen persona udemy">
        </div>
    </div>
</section>

DevTalles/Views/Shared/_SeccionInfo.cshtml
@using DevTalles.Data;


@{
    var img = "persona2.png";
    var img2 = "transforma.png";
}
<section class="container-xl py-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-5">
            <h2 class="fs-3">Devtalles <span class="text-success">business</span> </h2>
            <p>Plataforma creada y diseñada por estudiantes de la universidad Autonoma de Chinandega. Elaborada como proyecto final para Modulos en el Año 2023 </p>
            
        </div>
        <div class="col-md-5">
           <img class="img-fluid" src="@WC.RutaImagen@img" alt="imagen persona udemy for business">
        </div>
    </div>
</section>

<section class="container-xl py-5">
    <div class="row align-items-center justify-content-center">
        <div class="col-md-5 order-2 order-md-1">
            <img class="img-fluid" src="@WC.RutaImagen@img2" alt="imagen transforma">
        </div>
        <div class="col-md-5 mb-5 mb-md-0 order-1 order-md-2">
            <h2 class="fs-3">Transforma tu vida mediante la educación</h2>
            <p>Èsperamos continuar mejorando la aplicacion ya que hasta el momento faltan funcionalidades</p>
            <a href="#" class="btn btn-dark">Descubre cómo</a>
        </div>
    </div>
</section>